image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install && npm run build && make && npm i -g @nestjs/cli && nvm install 12.13.0
      rm /tmp/.npm-lock
    name: init
  - command: sudo docker-up
    name: docker
  - command: source ./gitpod.spin-up.sh
    name: terminal
  - command: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69 
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
