image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install && npm run build && make && npm i -g @nestjs/cli && nvm install 12.13.0
      rm /tmp/.npm-lock
    name: init
  - command: sudo docker-up
    name: docker
  - command: source ./gitpod.spin-up.sh
    name: terminal