version: "3.7"
services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    ports: 
      - 27017:27017
    restart: always
    networks: ["stack"]
    volumes:
      - mongodb1:/data/db
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
    networks: ["stack"]
  localstack:
    hostname: localstack
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=s3
    ports:
      - "4566"
    restart: always
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - localstack:/tmp/localstack
      - localstackdata:/tmp/localstack/data
    networks: ["stack"]
networks:
  stack:
volumes:
  mongodb1:
  redis:
  localstack:
  localstackdata:
