name: K6 load tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    name: K6 load tests
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-18.04
    env:
      MONGOOSE_HOST: localhost
      REDIS_HOST: localhost
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: http://localhost:4566
      AWS_BUCKET_NAME: demo-bucket
      AWS_S3_ENDPOINT: http://localhost:4566
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AUTH_CONFIG_SECRET: '{"config":[{"jwtFromRequest":"ExtractJwt.fromAuthHeaderAsBearerToken()","ignoreExpiration":false,"secretOrKey":"VALID_SECRET_KEY"},{"jwtFromRequest":"ExtractJwt.fromAuthHeaderAsBearerToken()","ignoreExpiration":false,"secretOrKey":"another_secret_key"}]}'
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
 
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      
      # We need execute the script manually because the code is mounted after the container is created
      - name: Create s3 bucket on localstack
        run: docker exec ${{job.services.localstack.id}} bash -c "`cat aws/bucket.sh`"
      
      - name: Start server and run tests
        run: |
          npm start > nest.log & npx wait-on http-get://localhost:3000/health
          ./k6 run --vus 100 --duration 60s tests/load/whisp-create.load.js
